//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbTeknikServisEntities : DbContext
    {
        public DbTeknikServisEntities()
            : base("name=DbTeknikServisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBLAdmin> TBLAdmin { get; set; }
        public virtual DbSet<TBLArizaDetay> TBLArizaDetay { get; set; }
        public virtual DbSet<TBLCari> TBLCari { get; set; }
        public virtual DbSet<TBLDepartman> TBLDepartman { get; set; }
        public virtual DbSet<TBLFaturaBilgi> TBLFaturaBilgi { get; set; }
        public virtual DbSet<TBLFaturaDetay> TBLFaturaDetay { get; set; }
        public virtual DbSet<TBLGider> TBLGider { get; set; }
        public virtual DbSet<TBLKategori> TBLKategori { get; set; }
        public virtual DbSet<TBLNotlarim> TBLNotlarim { get; set; }
        public virtual DbSet<TBLPersonel> TBLPersonel { get; set; }
        public virtual DbSet<TBLUrun> TBLUrun { get; set; }
        public virtual DbSet<TBLUrunHareket> TBLUrunHareket { get; set; }
        public virtual DbSet<TBLUrunKabul> TBLUrunKabul { get; set; }
        public virtual DbSet<TBLUrunTakip> TBLUrunTakip { get; set; }
    
        public virtual ObjectResult<urunKategori_Result> urunKategori()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<urunKategori_Result>("urunKategori");
        }
    }
}
